language: python

python:
  - "3.5"
install:
  - pip3 install -r ./requirements-dev.txt
script:
 - "python -m flake8 ./export_saved.py"
 - "python -m pytest -v ./tests"
#after_success:
  #- bash <(curl -s https://codecov.io/bash)
